<?php

namespace Database\Seeders;

use App\Models\AttributeCategory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AttributeCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        AttributeCategory::create([
            'category_id'=>1,
            'attribute_id'=>1
        ]);
        AttributeCategory::create([
            'category_id'=>1,
            'attribute_id'=>2
        ]);
        AttributeCategory::create([
            'category_id'=>1,
            'attribute_id'=>3
        ]);
        AttributeCategory::create([
            'category_id'=>1,
            'attribute_id'=>4
        ]);
        AttributeCategory::create([
            'category_id'=>1,
            'attribute_id'=>5
        ]);
        AttributeCategory::create([
            'category_id'=>1,
            'attribute_id'=>6
        ]);
        AttributeCategory::create([
            'category_id'=>1,
            'attribute_id'=>7
        ]);
        AttributeCategory::create([
            'category_id'=>1,
            'attribute_id'=>8
        ]);

        AttributeCategory::create([
            'category_id'=>2,
            'attribute_id'=>9
        ]);
        AttributeCategory::create([
            'category_id'=>2,
            'attribute_id'=>10
        ]);
        AttributeCategory::create([
            'category_id'=>2,
            'attribute_id'=>11
        ]);
        AttributeCategory::create([
            'category_id'=>2,
            'attribute_id'=>12
        ]);
        AttributeCategory::create([
            'category_id'=>2,
            'attribute_id'=>13
        ]);
        AttributeCategory::create([
            'category_id'=>2,
            'attribute_id'=>4
        ]);
        AttributeCategory::create([
            'category_id'=>2,
            'attribute_id'=>5
        ]);
        AttributeCategory::create([
            'category_id'=>2,
            'attribute_id'=>6
        ]);
        AttributeCategory::create([
            'category_id'=>2,
            'attribute_id'=>7
        ]);
        AttributeCategory::create([
            'category_id'=>2,
            'attribute_id'=>8
        ]);
        AttributeCategory::create([
            'category_id'=>2,
            'attribute_id'=>23
        ]);
        AttributeCategory::create([
            'category_id'=>3,
            'attribute_id'=>14
        ]);
        AttributeCategory::create([
            'category_id'=>3,
            'attribute_id'=>15
        ]);
        AttributeCategory::create([
            'category_id'=>3,
            'attribute_id'=>16
        ]);
        AttributeCategory::create([
            'category_id'=>3,
            'attribute_id'=>4
        ]);
        AttributeCategory::create([
            'category_id'=>3,
            'attribute_id'=>5
        ]);
        AttributeCategory::create([
            'category_id'=>3,
            'attribute_id'=>6
        ]);
        AttributeCategory::create([
            'category_id'=>3,
            'attribute_id'=>7
        ]);
        AttributeCategory::create([
            'category_id'=>3,
            'attribute_id'=>8
        ]);
        AttributeCategory::create([
            'category_id'=>3,
            'attribute_id'=>23
        ]);
        AttributeCategory::create([
            'category_id'=>4,
            'attribute_id'=>17
        ]);
        AttributeCategory::create([
            'category_id'=>4,
            'attribute_id'=>18
        ]);
        AttributeCategory::create([
            'category_id'=>4,
            'attribute_id'=>19
        ]);
        AttributeCategory::create([
            'category_id'=>4,
            'attribute_id'=>20
        ]);
        AttributeCategory::create([
            'category_id'=>4,
            'attribute_id'=>4
        ]);
        AttributeCategory::create([
            'category_id'=>4,
            'attribute_id'=>5
        ]);
        AttributeCategory::create([
            'category_id'=>4,
            'attribute_id'=>6
        ]);
        AttributeCategory::create([
            'category_id'=>4,
            'attribute_id'=>7
        ]);
        AttributeCategory::create([
            'category_id'=>4,
            'attribute_id'=>8
        ]);
        AttributeCategory::create([
            'category_id'=>4,
            'attribute_id'=>23
        ]);
        AttributeCategory::create([
            'category_id'=>5,
            'attribute_id'=>17
        ]);
        AttributeCategory::create([
            'category_id'=>5,
            'attribute_id'=>21
        ]);
        AttributeCategory::create([
            'category_id'=>5,
            'attribute_id'=>22
        ]);
        AttributeCategory::create([
            'category_id'=>5,
            'attribute_id'=>4
        ]);
        AttributeCategory::create([
            'category_id'=>5,
            'attribute_id'=>5
        ]);
        AttributeCategory::create([
            'category_id'=>5,
            'attribute_id'=>6
        ]);
        AttributeCategory::create([
            'category_id'=>5,
            'attribute_id'=>7
        ]);
        AttributeCategory::create([
            'category_id'=>5,
            'attribute_id'=>8
        ]);
        AttributeCategory::create([
            'category_id'=>5,
            'attribute_id'=>23
        ]);
    }
}
